[hotmart.selectors]
accept-cookies-btn = ".cookie-policy-accept-all"

[hotmart.selectors.courses]
course-title = ".membership-info-name"
purchased-card = ".purchase_list__block .purchase-card"
module-card = ".navigation-module"
module-index = ".navigation-module-index"
module-title = ".navigation-module-title"
lesson-card = ".navigation-page"
lesson-title = ".navigation-page-title"
clear-lesson-btn = ".btn-page-done:not(.btn-page-done-active)"
main-content-section = ".page-main-content"
video-section = ".content-page-video"
video-part = ".playlist-media"
video-part-active = ".playlist-media-active"
video-part-duration = ".playlist-media-time"

[hotmart.selectors.sso]
username-txt = "#username"
password-txt = "#password"
login-btn = "#text-btn-login"

[hotmart.urls]
consumer-portal = "https://consumer.hotmart.com/"
courses-portal = "https://consumer.hotmart.com/main"
origin = "https://cf-embed.play.hotmart.com"
referer = "https://cf-embed.play.hotmart.com/"

[hotmart.urls.patterns]
login-portal = "https://sso.hotmart.com/login*"
m3u8-master = "**/video/**/*.m3u8*"

[screenshot]
ext = "png"

[video]
format = "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4"

[downloads]
folder = "../../downloads"
